# Generated by Django 5.0.7 on 2024-08-10 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('clients_satisfaits', models.IntegerField()),
                ('projets_realises', models.IntegerField()),
                ('image', models.ImageField(upload_to='about_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
        migrations.CreateModel(
            name='connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('mecanicien', 'Mécanicien'), ('electricite', 'Électricité'), ('plomberie', 'Plomberie'), ('peinture', 'Peinture'), ('carrelage', 'Carrelage'), ('maintenance', 'Maintenance'), ('divers', 'Divers')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('typeservice', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DemandeService1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('demande', models.CharField(max_length=100, null=True)),
                ('delai', models.CharField(choices=[('30 minutes', '30 minutes'), ('1 heure', '1 heure'), ('2 heures', '2 heures'), ('1 jour', '1 jour'), ('2 jours', '2 jours'), ('5 jours', '5 jours')], max_length=100, null=True)),
                ('heure', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('ville', models.CharField(choices=[('Abidjan', 'Abidjan'), ('Yamoussoukro', 'Yamoussoukro'), ('Bouake', 'Bouake'), ('Daloa', 'Daloa'), ('San-Pedro', 'San-Pedro'), ('San-Rémi', 'San-Rémi'), ('Sassandra', 'Sassandra'), ('Soubre', 'Soubre'), ('Toumodi', 'Toumodi')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20000000, null=True)),
                ('indisponibilite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeService3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('question3', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=2000)),
                ('budjet', models.CharField(max_length=100)),
                ('disponibilite', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='oui', max_length=10)),
                ('contact_preference', models.CharField(choices=[('telephone', 'Téléphone'), ('email', 'Email')], default='email', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('typeservice', models.CharField(choices=[('nettoyage', 'Nettoyage à domicile'), ('mecanique', 'Mécanique'), ('menuiserie', 'Menuiserie')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EntrepriseArtisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=255)),
                ('structure_juridique', models.CharField(blank=True, max_length=255)),
                ('adresse_mail_entreprise', models.EmailField(max_length=254)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('numero_telephone_entreprise', models.CharField(max_length=20)),
                ('adresse_entreprise', models.CharField(max_length=255)),
                ('nom_prenom_artisan', models.CharField(max_length=255)),
                ('adresse_mail_artisan', models.EmailField(max_length=254)),
                ('numero_telephone_artisan', models.CharField(max_length=20)),
                ('adresse_artisan', models.CharField(max_length=255)),
                ('annees_experience', models.CharField(max_length=255)),
                ('fonction_dans_entreprise', models.CharField(max_length=255)),
                ('horaires_travail', models.CharField(max_length=255)),
                ('photo_artisan', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('social_links', models.JSONField()),
                ('quick_links', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('css_class', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('password1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='quote_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('Besoin', 'Besoin'), ('Localisation', 'Localisation'), ('Validation', 'Validation')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(help_text='Mentionner votre budget possible', max_length=255)),
                ('availability', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='oui', max_length=10)),
                ('contact_method', models.CharField(choices=[('telephone', 'Téléphone'), ('email', 'Email')], default='telephone', max_length=10)),
                ('status', models.CharField(choices=[('besoin', 'Besoin'), ('localisation', 'Localisation'), ('validation', 'Validation')], default='besoin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Besoin'), ('2', 'Localisation'), ('3', 'Validation')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('mecanique', 'Mécanique'), ('electricite', 'Électricité'), ('plomberie', 'Plomberie'), ('peinture', 'Peinture'), ('carrelage', 'Carrelage'), ('maintenance', 'Maintenance'), ('divers', 'Divers')], max_length=50)),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Forfait de Base', 'Pack 1: Abonnement de Base'), ('Forfait Avancé', 'Pack 2: Abonnement Avancé'), ('Forfait Premium', 'Pack 3: Abonnement Premium')], max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopbarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('nom_complet', models.CharField(max_length=255)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('annees_experience', models.PositiveIntegerField()),
                ('fonction', models.CharField(max_length=255)),
                ('horaires_travail', models.CharField(blank=True, max_length=255)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='NUMARTISAPP.entrepriseartisan')),
            ],
        ),
    ]
