# Generated by Django 5.0.3 on 2024-08-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0002_subscriptionpack_photo_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpack',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
